// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxNSZpXk5AU8PW3Noz9REMKCyEcQfEops',
    appId: '1:378852501011:web:3e706090cb84a87d0281e6',
    messagingSenderId: '378852501011',
    projectId: 'zidio-chat-app',
    authDomain: 'zidio-chat-app.firebaseapp.com',
    storageBucket: 'zidio-chat-app.appspot.com',
    measurementId: 'G-NELGY06XZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-jHRxNSXecYSMZXENnKCAzTqFoRqvxfE',
    appId: '1:378852501011:android:acbc734b4069bad60281e6',
    messagingSenderId: '378852501011',
    projectId: 'zidio-chat-app',
    storageBucket: 'zidio-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCycF1vVHmMTgcc6ZE-A_pP100uyL7Q3Ug',
    appId: '1:378852501011:ios:c1cc76d651d817050281e6',
    messagingSenderId: '378852501011',
    projectId: 'zidio-chat-app',
    storageBucket: 'zidio-chat-app.appspot.com',
    iosBundleId: 'com.example.zidioRealTimeChatFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCycF1vVHmMTgcc6ZE-A_pP100uyL7Q3Ug',
    appId: '1:378852501011:ios:c1cc76d651d817050281e6',
    messagingSenderId: '378852501011',
    projectId: 'zidio-chat-app',
    storageBucket: 'zidio-chat-app.appspot.com',
    iosBundleId: 'com.example.zidioRealTimeChatFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxNSZpXk5AU8PW3Noz9REMKCyEcQfEops',
    appId: '1:378852501011:web:3173dbaeb86fc5900281e6',
    messagingSenderId: '378852501011',
    projectId: 'zidio-chat-app',
    authDomain: 'zidio-chat-app.firebaseapp.com',
    storageBucket: 'zidio-chat-app.appspot.com',
    measurementId: 'G-1Y9H4DSF7T',
  );
}
